name: todo_app
description: My new Flutter Todo  app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  cloud_firestore: ^4.3.1
  dio: ^4.0.6
  equatable: ^2.0.5
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  
  
  firebase_database: ^10.0.10
  firebase_messaging: ^14.2.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1

  flutter_local_notifications: ^13.0.0 
  flutter_localizations:
    sdk: flutter

  flutter_offline: ^2.1.0  
  intl: ^0.17.0

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
