// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxNgtJvH293AAxIUmWpzOLLwyi5qP44hc',
    appId: '1:132180493407:web:eb636bc3aed219d64e87ea',
    messagingSenderId: '132180493407',
    projectId: 'todo-app-challenge',
    authDomain: 'todo-app-challenge.firebaseapp.com',
    storageBucket: 'todo-app-challenge.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfflhRYmsHGza9psuIh1tbpdSaUF91-t8',
    appId: '1:132180493407:android:76195772f939b2c04e87ea',
    messagingSenderId: '132180493407',
    projectId: 'todo-app-challenge',
    storageBucket: 'todo-app-challenge.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3vxik5IW12TzyszNrYxU56mcibI_TvNg',
    appId: '1:132180493407:ios:b0a3a1fd2b62b5ca4e87ea',
    messagingSenderId: '132180493407',
    projectId: 'todo-app-challenge',
    storageBucket: 'todo-app-challenge.appspot.com',
    iosClientId: '132180493407-9agfskbsrbv3b9g6il6fo6edquol7uu4.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.todo-app',
  );
}
